apiVersion: apps/v1
kind: Deployment
metadata:
  name: hairstyle-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hairstyle
  template:
    metadata:
      labels:
        app: hairstyle
    spec:
      containers:
        - name: hairstyle
          image: agrigorev/model-2025-hairstyle:v1
          args: ["lambda_function.lambda_handler"]
          ports:
            - containerPort: 8080
